package com.h2pro.accounting

import android.app.AlertDialog
import android.graphics.Color
import android.graphics.drawable.GradientDrawable
import android.os.Bundle
import android.text.InputType
import android.view.Gravity
import android.view.ViewGroup
import android.widget.*
import androidx.appcompat.app.AppCompatActivity
import java.text.SimpleDateFormat
import java.util.*

class MainActivity : AppCompatActivity() {
    private lateinit var db: AccountingDb
    private var currentUser = "1"
    private val navy = Color.rgb(20,42,58)
    private val bg = Color.rgb(247,249,251)
    private fun dp(v:Int)= (v*resources.displayMetrics.density).toInt()

    override fun onCreate(savedInstanceState: Bundle?) { super.onCreate(savedInstanceState); db=AccountingDb(this); showLogin() }
    private fun layout(title:String)=LinearLayout(this).apply{orientation=LinearLayout.VERTICAL;layoutDirection=LinearLayout.LAYOUT_DIRECTION_RTL;setBackgroundColor(bg);setPadding(dp(16),dp(16),dp(16),dp(16));window.statusBarColor=navy;addView(label(title,25,true,navy),margin(0,0,0,14))}
    private fun scroll(v:LinearLayout)=ScrollView(this).apply{addView(v,ViewGroup.LayoutParams(-1,-1))}
    private fun margin(l:Int,t:Int,r:Int,b:Int)=LinearLayout.LayoutParams(-1,-2).apply{setMargins(dp(l),dp(t),dp(r),dp(b))}
    private fun label(s:String,size:Int=16,bold:Boolean=false,color:Int=Color.DKGRAY)=TextView(this).apply{text=s;textSize=size.toFloat();setTextColor(color);gravity=Gravity.RIGHT;if(bold)setTypeface(typeface,1)}
    private fun field(h:String,number:Boolean=false)=EditText(this).apply{hint=h;textSize=17f;gravity=Gravity.RIGHT;setTextColor(Color.rgb(30,30,30));setHintTextColor(Color.rgb(105,105,105));setPadding(dp(14),dp(12),dp(14),dp(12));minHeight=dp(54);background=GradientDrawable().apply{shape=GradientDrawable.RECTANGLE;cornerRadius=dp(9).toFloat();setColor(Color.WHITE);setStroke(dp(2),Color.rgb(35,105,175))};if(number)inputType=InputType.TYPE_CLASS_NUMBER or InputType.TYPE_NUMBER_FLAG_DECIMAL}
    private fun btn(s:String,action:()->Unit)=Button(this).apply{text=s;isAllCaps=false;textSize=15f;setOnClickListener{action()}}
    private fun toast(s:String)=Toast.makeText(this,s,Toast.LENGTH_SHORT).show()
    private fun now()=SimpleDateFormat("yyyy-MM-dd HH:mm",Locale.US).format(Date())
    private fun money(v:Double)=String.format(Locale.US,"%,.2f",v)

    private fun showLogin(){
        val root=LinearLayout(this).apply{orientation=LinearLayout.VERTICAL;gravity=Gravity.CENTER;layoutDirection=LinearLayout.LAYOUT_DIRECTION_RTL;setPadding(dp(25),dp(30),dp(25),dp(30));setBackgroundColor(navy)}
        root.addView(label("H2pro",38,true,Color.WHITE),margin(0,0,0,6));root.addView(label("النظام المحاسبي المتكامل",18,false,Color.WHITE),margin(0,0,0,24))
        val card=LinearLayout(this).apply{orientation=LinearLayout.VERTICAL;setPadding(dp(22),dp(22),dp(22),dp(22));setBackgroundColor(Color.WHITE)}
        val u=field("رقم المستخدم");val p=field("كلمة المرور");p.inputType=InputType.TYPE_CLASS_TEXT or InputType.TYPE_TEXT_VARIATION_PASSWORD
        card.addView(label("رقم المستخدم",14,true,navy),margin(0,0,0,4));card.addView(u);card.addView(label("كلمة المرور",14,true,navy),margin(0,12,0,4));card.addView(p,margin(0,0,0,12))
        card.addView(btn("تسجيل الدخول"){if(db.login(u.text.toString(),p.text.toString())){currentUser=u.text.toString();db.audit(currentUser,"دخول","تسجيل الدخول");showHome()}else toast("رقم المستخدم أو كلمة المرور غير صحيحة")},margin(0,4,0,5));card.addView(btn("إلغاء"){finish()});root.addView(card,margin(0,8,0,0));setContentView(root)
    }
    private fun showHome(){val r=layout("H2pro المحاسبي");r.addView(label("القائمة الرئيسية",18,true),margin(0,0,0,10));listOf("تهيئة النظام" to ::showSetup,"إدارة النظام" to ::showSystem,"إدارة الأستاذ العام" to ::showLedger,"إدارة المخزون" to ::showInventory,"إدارة المشتريات" to ::showPurchases,"إدارة المبيعات" to ::showSales,"أنظمة وتقارير مساعدة" to ::showReports).forEach{r.addView(btn(it.first,it.second),margin(0,0,0,7))};r.addView(btn("تسجيل الخروج"){db.audit(currentUser,"خروج","تسجيل الخروج");showLogin()},margin(0,14,0,0));setContentView(scroll(r))}
    private fun section(title:String,items:List<Pair<String,()->Unit>>,back:()->Unit={showHome()}){val r=layout(title);items.forEach{r.addView(btn(it.first,it.second),margin(0,0,0,7))};r.addView(btn("رجوع",back),margin(0,15,0,0));setContentView(scroll(r))}
    private fun showSetup()=section("تهيئة النظام",listOf("بيانات السنة المالية" to ::years,"بيانات الشركة" to ::company,"بيانات المناطق" to ::regions,"بيانات العملات" to ::currencies))
    private fun years(){val r=layout("بيانات السنة المالية");val y=field("السنة المالية",true);val m=field("الشهور 1-12");val s=field("الحالة: مفتوحة / مغلقة");listOf(y,m,s).forEach{r.addView(it,margin(0,0,0,7))};r.addView(btn("إضافة"){val v=y.text.toString().toIntOrNull();if(v!=null&&db.saveYear(v,m.text.toString(),s.text.toString().ifBlank{"مفتوحة"})){toast("تمت الإضافة");years()}else toast("تعذر الحفظ")});r.addView(btn("بحث / تقرير"){report("تقرير السنوات",db.years(),::years)});r.addView(btn("رجوع",::showSetup),margin(0,15,0,0));setContentView(scroll(r))}
    private fun company(){val c=db.company();val r=layout("بيانات الشركة");val n=field("اسم الشركة");val p=field("رقم الهاتف");val a=field("العنوان");val l=field("الشعار / اسم ملف الشعار");n.setText(c.name);p.setText(c.phone);a.setText(c.address);l.setText(c.logo);listOf(n,p,a,l).forEach{r.addView(it,margin(0,0,0,7))};r.addView(btn("إضافة / تعديل"){db.saveCompany(n.text.toString(),p.text.toString(),a.text.toString(),l.text.toString());toast("تم حفظ بيانات الشركة")});r.addView(btn("حذف"){db.saveCompany("","","","");n.text.clear();p.text.clear();a.text.clear();l.text.clear();toast("تم حذف البيانات")});r.addView(btn("رجوع",::showSetup),margin(0,15,0,0));setContentView(scroll(r))}
    private fun regions(){val r=layout("بيانات المناطق");val c=field("الدولة");val p=field("المحافظة");val city=field("المدينة");val d=field("المنطقة");listOf(c,p,city,d).forEach{r.addView(it,margin(0,0,0,7))};r.addView(btn("إضافة"){db.saveRegion(c.text.toString(),p.text.toString(),city.text.toString(),d.text.toString());toast("تمت الإضافة")});r.addView(btn("بحث / تقرير"){report("تقرير المناطق",db.regions(),::regions)});r.addView(btn("رجوع",::showSetup),margin(0,15,0,0));setContentView(scroll(r))}
    private fun currencies(){val r=layout("بيانات العملات");val n=field("العملة");val e=field("السعر المعادل",true);val local=CheckBox(this).apply{text="العملة المحلية"};val rate=field("سعر التحويل",true);r.addView(n,margin(0,0,0,7));r.addView(e,margin(0,0,0,7));r.addView(local,margin(0,0,0,7));r.addView(rate,margin(0,0,0,8));r.addView(btn("إضافة"){db.saveCurrency(n.text.toString(),e.text.toString().toDoubleOrNull()?:1.0,local.isChecked,rate.text.toString().toDoubleOrNull()?:1.0);toast("تمت الإضافة")});r.addView(btn("بحث / تقرير"){report("تقرير العملات",db.currencies(),::currencies)});r.addView(btn("رجوع",::showSetup),margin(0,15,0,0));setContentView(scroll(r))}
    private fun showSystem()=section("إدارة النظام",listOf("بيانات المستخدمين" to ::users,"صلاحيات المستخدمين" to ::permissions,"تغيير كلمة السر" to ::password))
    private fun users(){val r=layout("بيانات المستخدمين");val no=field("رقم المستخدم");val name=field("اسم المستخدم");val pass=field("كلمة المرور");val role=field("الصلاحية");listOf(no,name,pass,role).forEach{r.addView(it,margin(0,0,0,7))};r.addView(btn("إضافة"){if(db.saveUser(no.text.toString(),name.text.toString(),pass.text.toString(),role.text.toString())){toast("تمت الإضافة");users()}else toast("رقم المستخدم موجود")});r.addView(btn("بحث / تقرير"){report("تقرير المستخدمين",db.userList(),::users)});r.addView(btn("رجوع",::showSystem),margin(0,15,0,0));setContentView(scroll(r))}
    private fun permissions(){val r=layout("صلاحيات المستخدمين");val no=field("رقم المستخدم");val modules=arrayOf("تهيئة النظام","إدارة النظام","الأستاذ العام","المخزون","المشتريات","المبيعات","التقارير");val checks=modules.map{CheckBox(this).apply{text=it;isChecked=true}};r.addView(no,margin(0,0,0,7));checks.forEach{r.addView(it)};r.addView(btn("حفظ الصلاحيات"){checks.forEachIndexed{i,c->db.savePermission(no.text.toString(),modules[i],c.isChecked)};toast("تم حفظ الصلاحيات")});r.addView(btn("رجوع",::showSystem),margin(0,15,0,0));setContentView(scroll(r))}
    private fun password(){val old=field("كلمة المرور الحالية");val n=field("كلمة المرور الجديدة");val c=field("تأكيد كلمة المرور");val box=LinearLayout(this).apply{orientation=LinearLayout.VERTICAL;addView(old);addView(n);addView(c)};AlertDialog.Builder(this).setTitle("تغيير كلمة السر").setView(box).setPositiveButton("حفظ"){_,_->if(db.login(currentUser,old.text.toString())&&n.text.toString()==c.text.toString()&&n.text.isNotBlank()){db.changePassword(currentUser,n.text.toString());toast("تم تغيير كلمة المرور")}else toast("بيانات كلمة المرور غير صحيحة")}.setNegativeButton("إلغاء",null).show()}
    private fun showLedger()=section("إدارة الأستاذ العام",listOf("تهيئة الأستاذ العام" to ::ledgerSetup,"مدخلات الأستاذ العام" to ::ledgerInputs,"عمليات الأستاذ العام" to ::ledgerOperations,"التقارير والكشوفات" to ::ledgerReports))
    private fun ledgerSetup(){val r=layout("تهيئة الأستاذ العام");r.addView(btn("شجرة الحسابات",::accounts));r.addView(label("الحسابات الرئيسية: أصول، خصوم، حقوق ملكية، إيرادات، مصروفات\nالحسابات الفرعية والعملات المحلية والأجنبية",16),margin(0,10,0,10));r.addView(btn("رجوع",::showLedger));setContentView(scroll(r))}
    private fun accounts(){val r=layout("شجرة الحسابات");r.addView(btn("إضافة حساب",::accountDialog));db.accounts().forEach{r.addView(label("${it.code} | ${it.name} | ${it.type} | ${if(it.level==1)"رئيسي" else "فرعي"}",16),margin(0,4,0,4))};r.addView(btn("رجوع",::showLedger),margin(0,15,0,0));setContentView(scroll(r))}
    private fun accountDialog(){val box=LinearLayout(this).apply{orientation=LinearLayout.VERTICAL};val code=field("رقم الحساب");val name=field("اسم الحساب");val type=Spinner(this).apply{adapter=ArrayAdapter(this@MainActivity,android.R.layout.simple_spinner_dropdown_item,arrayOf("أصول","خصوم","حقوق ملكية","إيرادات","مصروفات"))};val parent=field("رقم الحساب الأب (0 للرئيسي)",true);box.addView(code);box.addView(name);box.addView(type);box.addView(parent);AlertDialog.Builder(this).setTitle("إضافة حساب").setView(box).setPositiveButton("حفظ"){_,_->if(db.addAccount(code.text.toString(),name.text.toString(),type.selectedItem.toString(),parent.text.toString().toLongOrNull()?:0)){accounts()}else toast("تعذر إضافة الحساب")}.setNegativeButton("إلغاء",null).show()}
    private fun ledgerInputs()=section("مدخلات الأستاذ العام",listOf("ربط البنوك" to {bankDialog()},"ربط الصناديق" to {cashDialog()}),::showLedger)
    private fun bankDialog(){val b=LinearLayout(this).apply{orientation=LinearLayout.VERTICAL};val n=field("اسم البنك");val no=field("رقم الحساب");val c=field("العملة");listOf(n,no,c).forEach{b.addView(it,margin(0,0,0,7))};AlertDialog.Builder(this).setTitle("بيانات البنك").setView(b).setPositiveButton("حفظ"){_,_->db.addBank(n.text.toString(),no.text.toString(),c.text.toString());toast("تم حفظ البنك")}.setNegativeButton("إلغاء",null).show()}
    private fun cashDialog(){val b=LinearLayout(this).apply{orientation=LinearLayout.VERTICAL};val n=field("اسم الصندوق");val no=field("رقم الصندوق");val c=field("العملة");listOf(n,no,c).forEach{b.addView(it,margin(0,0,0,7))};AlertDialog.Builder(this).setTitle("بيانات الصندوق").setView(b).setPositiveButton("حفظ"){_,_->db.addCashbox(n.text.toString(),no.text.toString(),c.text.toString());toast("تم حفظ الصندوق")}.setNegativeButton("إلغاء",null).show()}
    private fun ledgerOperations()=section("عمليات الأستاذ العام",listOf("قيد يومية" to ::journal,"سند قبض" to {document("قبض")},"سند صرف" to {document("صرف")} ),::showLedger)
    private fun journal(){val r=layout("قيد يومية");val desc=field("البيان");val amount=field("المبلغ",true);val a=db.accounts();val sp=Spinner(this).apply{adapter=ArrayAdapter(this@MainActivity,android.R.layout.simple_spinner_dropdown_item,a.map{"${it.code} - ${it.name}"})};r.addView(desc);r.addView(sp,margin(0,5,0,5));r.addView(amount);r.addView(btn("حفظ القيد"){val v=amount.text.toString().toDoubleOrNull()?:0.0;if(v>0&&a.size>=2&&db.saveJournal(now(),desc.text.toString(),listOf(JournalLine(a[sp.selectedItemPosition].id,v,0.0),JournalLine(a[if(sp.selectedItemPosition==0)1 else 0].id,0.0,v)))){db.audit(currentUser,"قيد","${desc.text}");toast("تم حفظ القيد");showLedger()}else toast("القيد غير متوازن أو البيانات ناقصة")});r.addView(btn("رجوع",::showLedger),margin(0,15,0,0));setContentView(scroll(r))}
    private fun document(kind:String){val b=LinearLayout(this).apply{orientation=LinearLayout.VERTICAL};val name=field("الطرف / البيان");val amount=field("المبلغ",true);b.addView(name);b.addView(amount);AlertDialog.Builder(this).setTitle("سند $kind").setView(b).setPositiveButton("حفظ"){_,_->val v=amount.text.toString().toDoubleOrNull()?:0.0;if(v>0){db.addDocument(kind,name.text.toString(),v,now());db.audit(currentUser,kind,"$v");toast("تم حفظ السند")}}.setNegativeButton("إلغاء",null).show()}
    private fun ledgerReports()=section("التقارير والكشوفات",listOf("ميزان المراجعة" to ::trial,"قائمة الدخل" to ::income,"كشف الحسابات" to ::trial),::showLedger)
    private fun showInventory()=section("إدارة المخزون",listOf("الأصناف" to ::items,"حركة المخزون" to ::stockMovement,"جرد المخزون" to ::stockReport,"تقرير المخزون" to ::stockReport))
    private fun items(){val r=layout("الأصناف والمخزون");r.addView(btn("إضافة صنف",::itemDialog));db.items().forEach{r.addView(label(it),margin(0,4,0,4))};r.addView(btn("رجوع",::showInventory),margin(0,15,0,0));setContentView(scroll(r))}
    private fun itemDialog(){val b=LinearLayout(this).apply{orientation=LinearLayout.VERTICAL};val code=field("رمز الصنف");val name=field("اسم الصنف");val buy=field("سعر الشراء",true);val sale=field("سعر البيع",true);val qty=field("الكمية",true);val min=field("الحد الأدنى",true);listOf(code,name,buy,sale,qty,min).forEach{b.addView(it,margin(0,0,0,7))};AlertDialog.Builder(this).setTitle("إضافة صنف").setView(b).setPositiveButton("حفظ"){_,_->if(db.addItem(code.text.toString(),name.text.toString(),buy.text.toString().toDoubleOrNull()?:0.0,sale.text.toString().toDoubleOrNull()?:0.0,qty.text.toString().toDoubleOrNull()?:0.0,min.text.toString().toDoubleOrNull()?:0.0))items()else toast("رمز الصنف موجود")}.setNegativeButton("إلغاء",null).show()}
    private fun stockMovement(){report("حركة المخزون",listOf("حركات الشراء والبيع والجرد"),::showInventory)}
    private fun stockReport(){report("تقرير المخزون",listOf("قيمة المخزون: ${money(db.inventoryValue())} ريال","أصناف تحت الحد: ${db.lowStock()}"),::showInventory)}
    private fun showPurchases()=section("إدارة المشتريات",listOf("فاتورة شراء" to {document("شراء")},"الموردون" to {contacts("مورد")},"تقرير المشتريات" to ::purchaseReport))
    private fun showSales()=section("إدارة المبيعات",listOf("فاتورة بيع" to {document("بيع")},"العملاء" to {contacts("عميل")},"تقرير المبيعات" to ::salesReport))
    private fun contacts(kind:String){val r=layout(if(kind=="عميل")"العملاء" else "الموردون");r.addView(btn("إضافة",{contactDialog(kind)}));db.contacts(kind).forEach{r.addView(label(it),margin(0,4,0,4))};r.addView(btn("رجوع",if(kind=="عميل")::showSales else ::showPurchases),margin(0,15,0,0));setContentView(scroll(r))}
    private fun contactDialog(kind:String){val b=LinearLayout(this).apply{orientation=LinearLayout.VERTICAL};val n=field("الاسم");val p=field("الهاتف");val a=field("العنوان");listOf(n,p,a).forEach{b.addView(it,margin(0,0,0,7))};AlertDialog.Builder(this).setTitle("إضافة $kind").setView(b).setPositiveButton("حفظ"){_,_->db.addContact(kind,n.text.toString(),p.text.toString(),a.text.toString());contacts(kind)}.setNegativeButton("إلغاء",null).show()}
    private fun purchaseReport(){report("تقرير المشتريات",listOf("الإجمالي: ${money(db.sumDocuments("شراء"))} ريال"),::showPurchases)}
    private fun salesReport(){report("تقرير المبيعات",listOf("الإجمالي: ${money(db.sumDocuments("بيع"))} ريال"),::showSales)}
    private fun showReports()=section("أنظمة وتقارير مساعدة",listOf("ميزان المراجعة" to ::trial,"قائمة الدخل" to ::income,"تقرير المبيعات" to ::salesReport,"تقرير المشتريات" to ::purchaseReport,"سجل العمليات" to ::audit))
    private fun trial(){report("ميزان المراجعة",db.trialBalance().ifEmpty{listOf("لا توجد حركة محاسبية بعد")},::showReports)}
    private fun income(){val sales=db.sumDocuments("بيع");val purchases=db.sumDocuments("شراء");val expenses=db.sumDocuments("صرف");report("قائمة الدخل",listOf("المبيعات: ${money(sales)} ريال","المشتريات: ${money(purchases)} ريال","المصروفات: ${money(expenses)} ريال","صافي الربح: ${money(sales-purchases-expenses)} ريال"),::showReports)}
    private fun audit(){report("سجل العمليات",db.auditLog().ifEmpty{listOf("لا توجد عمليات مسجلة")},::showReports)}
    private fun report(title:String,rows:List<String>,back:()->Unit){val r=layout(title);rows.forEach{r.addView(label(it,16),margin(0,5,0,5))};r.addView(btn("رجوع",back),margin(0,15,0,0));setContentView(scroll(r))}
}
